Sprint 5/step 1
ngrvsn/react-burger pull request #5
Opened 2023-11-01 22:38 UTC by ngrvsn

2023-11-02 04:54 UTC, ArslanMustafin requested changes
## Code Review

Здравствуйте!

Отличная работа. 🔥

### **Вы молодец!**

- Сборка и запуск проекта выполняются без ошибок;
- Реализована страница ленты заказов;
- Теперь пользователь может посмотреть историю заказов;

### **Но есть несколько замечаний, которые нужно исправить:**

- Нужно поправить верстку в соответствии с макетом.

  - <https://disk.yandex.com/i/SAuYll8PtPcmzQ>;
  - <https://disk.yandex.com/i/vGy_yPfD6urx8A>;
  - <https://disk.yandex.com/i/hYOt7cCF0RQBqA>;
  - <https://disk.yandex.com/i/XfDQDQn9v__PdA>;
  - <https://disk.yandex.com/i/T0tE7nfU_h23ug> - в колонке `В роботе` номер заказа должен быть белого цвета;

- Не подтянулись шрифты. <https://disk.yandex.com/i/d7mhFoYLgmz-zQ>;

- У вас не закрывается сокет соединение, когда пользователь открывает в новой вкладке страницу `/feed/:id` и `/profile/orders/:id` и покидает их (сокет должен закрываться когда пользователь покидает эти новые страницы, со страницами `/feed`, `/profile/orders` всё работает хорошо, а вот с ними нет).

- В запросе `POST /orders` нужно чтобы id у булок были в начале и в конце массива - <https://disk.yandex.com/i/RaYsn1drDg_xGQ>;

- При посещении главной страницы у вас каждый раз вызывается запрос `GET /ingredients`, а должен вызываться 1 раз (Перенесите вызов, в компонент app, а в компоненте `burger-ingredients` уберите). Тоже самое касается и запроса на получение данных о пользователе `GET /user`.

### **Сделает код лучше:**

- Вам не нужно указывать тип у стейта в хуке useSelector) `useSelector((store: RootState) => ...)`, вам нужно использовать типизированный хук.

- Перед отправкой работы убедитесь в том, что весь неиспользуемый код удален.

- Стоит обращать внимание на предупреждения в терминале, в котором запущен проект. Это хорошие рекомендации, которых следовало бы придерживаться. В противном случае, лучше отключить линтер у строки (куска кода) eslint-disable. Так же добавить комментарий (TODO), объясняющий причину блокировки линтера в данном месте. Суть в том, что мы стараемся писать более чистый код, а если видим, что порой выскакивают предупреждения того же линтера, то оставляем комментарий, объясняющий причину. В коммерческой разработке, когда есть целая команда разработчиков, работающих над одним проектом, эта рекомендация послужит правилом хорошего тона. Неплохая статься по поводу локального отключения линтера: <https://learn.coderslang.com/ru/0023-eslint-disable-for-specific-lines-files-and-folders>

### **_Подробно эти и более мелкие замечания, отмечены в коде._**

### **После исправления всех замечаний, работа будет принята)**

2023-11-02 04:54 UTC, ArslanMustafin commented on src/components/burger-constructor/BurgerConstructor.tsx
> +  );
**Можно лучше:**

Лучше написать так:

```js
const { bun, ingredients } = useMemo(() => {
  return {
    bun: data.find(item => item.type === 'bun'),
    ingredients: data.filter(item => item.type !== 'bun'),
  };
}, [data]);
```

2023-11-02 04:54 UTC, ArslanMustafin commented on src/components/burger-ingredients/BurgerIngredients.tsx
> +  }, []);
**Надо исправить:**

Вы работает в реакте, тут virtualDom, лучше подцепить `onClick` через `jsx`. Эффект будет 1 и тот же, а вот кода в разы меньше.

2023-11-02 04:54 UTC, ArslanMustafin commented on src/components/burger-ingredients/BurgerIngredients.tsx
> +  };
**Можно лучше:**

Попробуйте использовать библиотеку `react-intersection-observer`

2023-11-02 04:54 UTC, ArslanMustafin commented on src/components/feed-archive/feed-info/feed-info.tsx
> +    const ordersUser = useSelector((state: RootState) => state.orderTrackingUser.orders);
**Можно лучше:**

Вам не нужно указывать тип у стейта в хуке useSelector) `useSelector((store: RootState) => ...)`, вы должны использовать типизированный хук.

2023-11-02 04:54 UTC, ArslanMustafin commented on src/components/feed-archive/feed-info/feed-info.tsx
> +        const filteredOrders = (location.pathname.includes('/profile/') ? ordersUser : ordersPublic).filter((item: TOrdersSectionProps) => item._id === path);
**Можно лучше:**

тут лучше использовать `find`, а не `filter`.

https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Global_Objects/Array/find

2023-11-02 04:54 UTC, ArslanMustafin commented on src/components/feed-archive/feed-info/feed-info.tsx
> +                dispatch(WebSocketStart("wss://norma.nomoreparties.space/orders/all"));
**Надо исправить:**

Нужно вынести `url` в сами экшены, чтобы не писать их каждый раз при вызове экшена.
А также нужно вынести эти `url` в константы.

2023-11-02 04:54 UTC, ArslanMustafin commented on src/components/feed-archive/feed-info/feed-info.tsx
> +    const publicOrUser = (): void => {
**Можно лучше:**

Советую подумать над названием функции, сейчас по названию не понятно что эта функция делает.

2023-11-02 04:54 UTC, ArslanMustafin commented on src/components/feed-archive/feed-info/feed-info.tsx
> +                        {orderStatus()}
**Можно лучше:**

Здесь и далее, лучше не вызывать функции в `jsx`, не всегда понятно что тут будет за контент. Вынесите результат функции в переменные, и уже их используйте в `jsx`.

2023-11-02 04:54 UTC, ArslanMustafin commented on src/components/feed-archive/feed-info/feed-info.tsx
> +                                }, 0)}
**Надо исправить:**

Нужно вынести эти вычисления в переменную

2023-11-02 04:54 UTC, ArslanMustafin commented on src/components/feed-archive/feed-section/feed-section.tsx
> +    const readyOrders2 = last10Orders2.filter(item => item.status === 'done');
**Надо исправить:**

не нужно разделять заказы на несколько групп, вам достаточно обрезать их 1 раз, 2 колонки можно сделать с помощью верстки.

2023-11-02 04:54 UTC, ArslanMustafin commented on src/components/feed-archive/feed/feed.tsx
> +            dispatch(WebSocketStart("wss://norma.nomoreparties.space/orders/all"));
**Надо исправить:**

Нужно вынести `url` в сами экшены, чтобы не писать их каждый раз при вызове экшена.
А также нужно вынести эти `url` в константы.

2023-11-02 04:54 UTC, ArslanMustafin commented on src/components/feed-archive/feed/feed.tsx
> +            dispatch(WebSocketStartUser(`wss://norma.nomoreparties.space/orders?token=${getCookie("token")}`));
**Надо исправить:**

Нужно вынести `url` в сами экшены, чтобы не писать их каждый раз при вызове экшена.
А также нужно вынести эти `url` в константы.

2023-11-02 04:54 UTC, ArslanMustafin commented on src/components/feed-archive/feed/feed.tsx
> +                        const displayedIngredients = ingredients.slice(0, 6);
**Надо исправить:**

Функционал полностью идентичен, не нужно делать такие огромные куски кода, ради разных массивов.
Лучше создать ещё 1 переменную и там уже выбрать нужный массив.

2023-11-02 21:43 UTC, ngrvsn commented
Доброй ночи. Закрытие сокета при переходе с отдельных страниц сделать пытался, ничего не получилось, к слову, в чеклисте указано только закрытие сокета при уходе с экранов, отдельные страницы не указаны

>>>Работа с WebSocket выполняется верно:
Сокет-соединение открывается, когда пользователь переходит на экраны «Лента заказов» или «История заказов», и
закрывается, когда пользователь покидает их.

Запрос я дописал
![image](https://github.com/ngrvsn/react-burger/assets/129547100/2a63dc06-9b99-4905-a5cb-7bf24f6b79c5)
Только теперь вот так считаются заказы других пользователей
![image](https://github.com/ngrvsn/react-burger/assets/129547100/439eec0c-66b6-4b9b-a411-649ee3785def)
А вот так мои заказы
![image](https://github.com/ngrvsn/react-burger/assets/129547100/063da696-e91e-450f-96ba-3478322caa0f)
Если я уберу перемножение в компоненте в заказах других юзеров получится 1 булка

2023-11-02 21:49 UTC, ngrvsn commented on src/components/burger-constructor/BurgerConstructor.tsx
> +  );
> **Можно лучше:**
> 
> Лучше написать так:
> 
> ```js
> const { bun, ingredients } = useMemo(() => {
>   return {
>     bun: data.find(item => item.type === 'bun'),
>     ingredients: data.filter(item => item.type !== 'bun'),
>   };
> }, [data]);
> ```

Доброй ночи. Закрытие сокета при переходе с отдельных страниц сделать пытался, ничего не получилось, к слову, в чеклисте указано только закрытие сокета при уходе с экранов, отдельные страницы не указаны

>>>Работа с WebSocket выполняется верно:
Сокет-соединение открывается, когда пользователь переходит на экраны «Лента заказов» или «История заказов», и
закрывается, когда пользователь покидает их.

Запрос я дописал
![image](https://github.com/ngrvsn/react-burger/assets/129547100/319bbfcb-7822-4408-8234-58b81ba6115a)
Только теперь вот так считаются заказы других пользователей
![image](https://github.com/ngrvsn/react-burger/assets/129547100/5a255e95-7563-4208-9a8e-72fe28f5f19c)
А вот так мои заказы
![image](https://github.com/ngrvsn/react-burger/assets/129547100/a2f83264-71af-4d71-819f-5fc6a3fcf3d3)
Если я уберу перемножение в компоненте в заказах других юзеров получится 1 булка

2023-11-03 10:57 UTC, ArslanMustafin approved these changes
## Code Review

Здравствуйте!

Хорошая работа. 

### **Вы молодец! Работа принята, удачи в дальнейшем обучении!**

- Практически все замечания были исправлены;

### **Сделает работу лучше:**

- Когда будет время поправьте верстку в соответствии с макетом. На реальных проектах, иногда верстка будет играть более важную роль чем логика.

- Исправить следующие замечания:
  - <https://github.com/ngrvsn/react-burger/pull/5#discussion_r1379586546>;

2023-11-03 10:57 UTC, ArslanMustafin commented on src/components/feed-archive/feed-info/feed-info.tsx
> +/* eslint-enable */
**Можно лучше:**

Лучше написать вот так, 

```js
useEffect(() => {
  const storedOrderData = localStorage.getItem('currentOrder');
  if (storedOrderData) {
      const currentOrder = JSON.parse(storedOrderData);
      dispatch(updateOrder(currentOrder));
  }
// eslint-disable-next-line react-hooks/exhaustive-deps
}, []);
```

Старайтесь убирать линтер именно на строчке, а не на всём куске кода. Да и `dispatch` можно занести в зависимость, хуже от этого не будет.

2023-11-03 10:57 UTC, ArslanMustafin commented on src/components/feed-archive/feed/feed.tsx
> +    const statusText = orderStatus;
**Можно лучше:**

а зачем создавать дополнительную функцию?

2023-11-03 10:57 UTC, ArslanMustafin commented on src/components/feed-archive/feed/feed.tsx
> +    const ordersSplit = (item: TOrdersSectionProps) => {
**Можно лучше:**

это кусок кода лучше вынести в отдельный компонент, а не делать из этого функцию.

2023-11-03 10:57 UTC, ArslanMustafin commented on src/components/feed-archive/feed/feed.tsx
> +                    userOrders.slice().reverse().map(ordersSplit)
**Рекомендую исправить:**

получите данные до `jsx`, нежелательно такие операции делать в `jsx`.

```js
const orders = useMemo(() => {
  if(match) {
    return publicOrders
  }

  return userOrders.toReversed()
}, [match, publicOrders, userOrders])

return (
  <>
    // ...
  <>
)
```



https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Global_Objects/Array/toReversed

2023-11-03 10:57 UTC, ArslanMustafin commented on src/components/feed-archive/feed-section/feed-section.tsx
> +///Я не придумал что тут сделать, пытался делить общую переменную внутри разметки, консоль ошибку бьет на неуникальные пропсы
1) https://disk.yandex.com/i/nQHB8zNgaXHCyA - Подготовить код, там всё достаточно просто;
2) https://disk.yandex.com/i/A26PLFyvKmjVKw - поставить вот такие стили контейнеру `readyColumn`

2023-11-03 14:56 UTC, ngrvsn commented on src/components/feed-archive/feed-section/feed-section.tsx
> +///Я не придумал что тут сделать, пытался делить общую переменную внутри разметки, консоль ошибку бьет на неуникальные пропсы
![image](https://github.com/ngrvsn/react-burger/assets/129547100/f5a08b09-9fb1-43f3-bc45-0683e6095abb)
Даже не подумал что можно через свойства в 2 колонки слепить, спасибо

2023-11-03 14:56 UTC, ngrvsn commented on src/components/feed-archive/feed/feed.tsx
> +                    userOrders.slice().reverse().map(ordersSplit)
![image](https://github.com/ngrvsn/react-burger/assets/129547100/c1138592-4ea9-4c18-9f2e-a4f771fed895)

2023-11-03 15:10 UTC, ngrvsn commented on src/components/feed-archive/feed/feed.tsx
> +    const statusText = orderStatus;
Поплавило чуть, с 2 дня до 5 утра просидел с мыслью "сейчас доделаю немного осталось", в итоге занимался часть времени непонятно чем вроде закрытия сокета после закрытия модалки что не требовалось) Спасибо за ревью, ссылки и помощь с правками, буду стараться доделать, понимаю что проект с кривым дизайном в портфолио = такое себе

2023-11-14 20:04 UTC, closed without merging